# Generated by Django 3.0.8 on 2020-07-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('due_date', models.DateField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
